---
title: "Collaborate"
author: "Brendan Lehman"
date: "December 1, 2017"
output: html_document
---
# This is our analysis!

Breaking news! I just updated our manuscript!

### NYC flight data
```{r NYC Import}
library(tidyverse)
library(nycflights13) #install.packages("nycflights13")

flights
#Jan 1 data

flights %>% 
  filter(month == 1, 
         day == 1)

head(flights)
<<<<<<< HEAD
ggplot(data=(flights %>% group_by(month)), aes(x=month))+
         geom_histogram()
=======

ggplot(data=flights, aes(x=hour))+
         geom_density(kernel="gaussian")+
          theme_bw()
```
```{r Map}
library(leaflet)#load.packages

>>>>>>> 7121dc5e7c26b84363b6b691c995550bb038f22b
```
### Tibble awesomeness
```{r}
library(tidyverse)
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

tbl<-gapminder %>% 
  group_by(country) %>% 
  nest() %>% 
  mutate(
    mdl= map(data, function(x) lm(gdpPercap ~ year, data = x))
    #gplot = ggplot2(data, aes(x=year, y=gdpPercap))
  )

tbl$data[[1]]
```


